### ISSUE TITLE
Documentation Update Needed

### ISSUE THREAD

**Issue by billglick** [ncsa/puppet-profile_additional_packages#2]
A few documentation issues:

1. The README.md file refers to `profile_additional_repos` instead of `profile_additional_packages`.
2. Would be good to clean up the class docstrings so that the examples match yaml formatting we want (spacing, double quotes, etc).
3. Generate and link in REFERENCE.md to README.md

**Comment by cpitcel** [comment]
Updated the README and generated the REFERENCE file
